include_guard()

set(MAIN_SOURCE_FILES
	Application/DukeForge.h
	Application/DukeForge.cpp
	Application/SettingsManager.h
	Application/SettingsManager.cpp
	Game/File/GameFile.h
	Game/File/GameFile.cpp
	Game/File/GameFileFactoryRegistry.h
	Game/File/GameFileFactoryRegistry.cpp
	Game/File/Animation/Animation.h
	Game/File/Animation/Animation.cpp
	Game/File/Animation/ANM/AnimationANM.h
	Game/File/Animation/ANM/AnimationANM.cpp
	Game/File/Animation/ANM/ColourCycleInfo.cpp
	Game/File/Animation/ANM/LargePageDescriptor.cpp
	Game/File/Art/Art.h
	Game/File/Art/Art.cpp
	Game/File/Art/Tile.h
	Game/File/Art/Tile.cpp
	Game/File/Art/TileNames.cpp
	Game/File/Group/Group.h
	Game/File/Group/Group.cpp
	Game/File/Group/GroupFile.h
	Game/File/Group/GroupFile.cpp
	Game/File/Group/GroupUtilities.h
	Game/File/Group/GRP/GroupGRP.h
	Game/File/Group/GRP/GroupGRP.cpp
	Game/File/Group/SSI/GroupSSI.h
	Game/File/Group/SSI/GroupSSI.cpp
	Game/File/Map/BuildConstants.h
	Game/File/Map/Map.h
	Game/File/Map/Map.cpp
	Game/File/Map/Partition.h
	Game/File/Map/Partition.cpp
	Game/File/Map/PlayerSpawn.h
	Game/File/Map/PlayerSpawn.cpp
	Game/File/Map/SectorItem.h
	Game/File/Map/SectorItem.cpp
	Game/File/Map/Sector.h
	Game/File/Map/Sector.cpp
	Game/File/Map/Sprite.h
	Game/File/Map/Sprite.cpp
	Game/File/Map/TaggedItem.h
	Game/File/Map/TaggedItem.cpp
	Game/File/Map/TexturedItem.h
	Game/File/Map/TexturedItem.cpp
	Game/File/Map/Velocity3D.h
	Game/File/Map/Velocity3D.cpp
	Game/File/Map/Wall.h
	Game/File/Map/Wall.cpp
	Game/File/MIDI/MIDI.h
	Game/File/MIDI/MIDI.cpp
	Game/File/MIDI/MIDIByteBufferReadStream.h
	Game/File/MIDI/MIDIByteBufferReadStream.cpp
	Game/File/MIDI/MIDIByteBufferWriteStream.h
	Game/File/MIDI/MIDIByteBufferWriteStream.cpp
	Game/File/Palette/ColourTable.h
	Game/File/Palette/ColourTable.cpp
	Game/File/Palette/Palette.h
	Game/File/Palette/Palette.cpp
	Game/File/Palette/ACT/PaletteACT.h
	Game/File/Palette/ACT/PaletteACT.cpp
	Game/File/Palette/CSS/PaletteCSS.h
	Game/File/Palette/CSS/PaletteCSS.cpp
	Game/File/Palette/DAT/PaletteDAT.h
	Game/File/Palette/DAT/PaletteDAT.cpp
	Game/File/Palette/DAT/ShadeTable.cpp
	Game/File/Palette/DAT/SwapTable.cpp
	Game/File/Palette/DAT/TranslucencyTable.cpp
	Game/File/Palette/GPL/PaletteGPL.h
	Game/File/Palette/GPL/PaletteGPL.cpp
	Game/File/Palette/JASC/PaletteJASC.h
	Game/File/Palette/JASC/PaletteJASC.cpp
	Game/File/Palette/KPL/PaletteKPL.h
	Game/File/Palette/KPL/PaletteKPL.cpp
	Game/File/Palette/PAL/PalettePAL.h
	Game/File/Palette/PAL/PalettePAL.cpp
	Game/File/Palette/TXT/PaletteTXT.h
	Game/File/Palette/TXT/PaletteTXT.cpp
	Game/File/Sound/Sound.h
	Game/File/Sound/Sound.cpp
	Game/File/Sound/VOC/SoundVOC.h
	Game/File/Sound/VOC/SoundVOC.cpp
	Game/File/Sound/WAV/SoundWAV.h
	Game/File/Sound/WAV/SoundWAV.cpp
	Game/File/Zip/Zip.h
	Game/File/Zip/Zip.cpp
	Game/NoCDCracker.h
	Game/NoCDCracker.cpp
	Project.h
)

set(GUI_SOURCE_FILES
	GUI/Console/ConsolePanel.h
	GUI/Console/ConsolePanel.cpp
	GUI/Console/Logging/CustomLogTextControl.h
	GUI/Console/Logging/CustomLogTextControl.cpp
	GUI/Console/Logging/LogSinkWX.h
	GUI/Console/Logging/LogSinkWX.cpp
	GUI/Console/Logging/PreformattedLogFormatter.h
	GUI/Console/Logging/PreformattedLogFormatter.cpp
	GUI/DukeForgeApplication.h
	GUI/DukeForgeApplication.cpp
	GUI/DukeForgeFrame.h
	GUI/DukeForgeFrame.cpp
	GUI/Game/File/GameFilePanel.h
	GUI/Game/File/GameFilePanel.cpp
	GUI/Game/File/GameFilePanelFactoryRegistry.h
	GUI/Game/File/GameFilePanelFactoryRegistry.cpp
	GUI/Game/File/Group/GroupPanel.h
	GUI/Game/File/Group/GroupPanel.cpp
	GUI/Game/File/Group/GRP/GroupPanelGRP.h
	GUI/Game/File/Group/GRP/GroupPanelGRP.cpp
	GUI/Game/File/Group/SSI/GroupPanelSSI.h
	GUI/Game/File/Group/SSI/GroupPanelSSI.cpp
	GUI/Game/File/Group/SSI/SunstormInteractiveMetadataPanel.h
	GUI/Game/File/Group/SSI/SunstormInteractiveMetadataPanel.cpp
	GUI/Game/File/Palette/ColourTablePanel.h
	GUI/Game/File/Palette/ColourTablePanel.cpp
	GUI/Game/File/Palette/PalettePanel.h
	GUI/Game/File/Palette/PalettePanel.cpp
	GUI/Game/File/Palette/ACT/PalettePanelACT.h
	GUI/Game/File/Palette/ACT/PalettePanelACT.cpp
	GUI/Game/File/Palette/CSS/PalettePanelCSS.h
	GUI/Game/File/Palette/CSS/PalettePanelCSS.cpp
	GUI/Game/File/Palette/DAT/PalettePanelDAT.h
	GUI/Game/File/Palette/DAT/PalettePanelDAT.cpp
	GUI/Game/File/Palette/GPL/PalettePanelGPL.h
	GUI/Game/File/Palette/GPL/PalettePanelGPL.cpp
	GUI/Game/File/Palette/JASC/PalettePanelJASC.h
	GUI/Game/File/Palette/JASC/PalettePanelJASC.cpp
	GUI/Game/File/Palette/KPL/PalettePanelKPL.h
	GUI/Game/File/Palette/KPL/PalettePanelKPL.cpp
	GUI/Hyperlink.h
	GUI/Hyperlink.cpp
	GUI/MetadataPanel.h
	GUI/MetadataPanel.cpp
	GUI/Project/ProjectPanel.h
	GUI/Project/ProjectPanel.cpp
	GUI/Releases/ReleaseNotesPanel.h
	GUI/Releases/ReleaseNotesPanel.cpp
	GUI/SettingPanel.h
	GUI/SettingPanel.cpp
	GUI/Settings/SettingsManagerPanel.h
	GUI/Settings/SettingsManagerPanel.cpp
	GUI/WXUtilities.h
	GUI/WXUtilities.cpp
)

list(APPEND SOURCE_FILES ${MAIN_SOURCE_FILES} ${MAIN_SOURCE_FILES_${PLATFORM_UPPER}})

list(APPEND SOURCE_FILES ${GUI_SOURCE_FILES})

list(TRANSFORM SOURCE_FILES PREPEND "${_SOURCE_DIRECTORY}/")

source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/${_SOURCE_DIRECTORY}" PREFIX "Source Files" FILES ${SOURCE_FILES})
